### PR TITLE
update to font-awesome 4.6.3

### PR DESCRIPTION
**Pull request by fuzzmz**

### CODE REVIEW

**Comment by sbadia** [comment]
@fuzzmz thanks for this PR! the `4.6.3` was released the [2016/05/17](https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.6.3), can we update this PR?

**Comment by fuzzmz** [comment]
I'll update this PR to the latest version this evening.

**Comment by fuzzmz** [comment]
@bmcorser, any plans on merging this? Could use some of the new icons added in the latest release without having to rely on my fork of pelicanfly.

**Comment by bmcorser** [comment]
Apologies for the delay, published to PyPI as version [`0.4.4`](https://pypi.python.org/pypi/pelicanfly/0.4.4)

**Pull request merged**
